const swaggerAutogen = require('swagger-autogen')()

swaggerAutogen('./swagger-output.json', ['./app.js'],
    {
        info: {
            version: "1.0.0",
            title: "My API",
            description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
        },
        host: "localhost:3000",
        definitions: {
            Event: {
                $id: 1,
                $name: "Tech Conference 2025",
                $date: "2025-05-15",
                $location: "Oslo Convention Center",
                $capacity: 500,
                $isOnline: false,
                $createdAt: "2025-03-03T16:50:42.000Z",
                $updatedAt: "2025-03-03T16:50:42.000Z"
            }
        }
    }
)